version: '3.9'
name: parking-control

services:
  spring-api:
    build:
      context: ../
      dockerfile: ./docker/dockerfile.spring.dev
    ports:
      - 8000:8000
    depends_on:
      db-postgresql:
        condition: service_healthy
    networks:
      - app-network

  db-postgresql:
    image: postgres:15.2-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: development
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  dbm-adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db-postgresql:
        condition: service_healthy
    networks:
      - app-network


networks:
  app-network:


volumes:
  db-data:
